### ISSUE TITLE
Create contact screen

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#115]
### Create contact screen

This screen serves as the main point for an user to add a new contact to their contacts list. It's composed mainly by a form, where the contact's information can be filled in.

First, the user must choose what type of contact they want to create: Company or Person. It's also necessary to provide a Node ID in order to proceed with the creation of a contact, since it's the ID that will be used to identify the contact within the network.

Please notice that even though the object sent to the API endpoint that handles the contact creation, it's important to switch the labels names when the contact type is changed, as they have a slight difference depending on the type of the contact.

As soon as the contact creation is successful, the user is redirected to the initial contacts screen, which is the same as the contacts list screen, but with the new contact added to the list.

#### Development

The API route that handles the contact creation accepts a POST request with the following parameters, in JSON format. The endpoint is `/contacts/create`. The payload format looks like this:

```
{
    "type": 0,
    "name": "John Smith",
    "email": "johnny_smith@example.com",
    "postal_address": "Smithstreet 272, 1030 Vienna",
    "public_key": "12D3KooWBN48JhNXAKhKxbUVM1YXRrHTfPYxjWiGpcKYGuR77cy3",
    "date_of_birth_or_registration": "1998-10-17",
    "country": "AT",
    "city": "Vienna",
    "identification_number": "12315412312",
    "avatar": "some_file_upload_id",
    "proof_document": "some_file_upload_id"
}
```

Important: the file upload endpoint for this domain is not yet defined in our API documentation, so for now we must use a placeholder, and this task is going to be updated as soon as the endpoint is defined.

#### Files

[Create.tsx](https://github.com/BitcreditProtocol/E-Bill-frontend/blob/main/src/pages/contacts/Create.tsx)

#### Design references

[Create person contact](https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2625-6319&node-type=canvas&m=dev)

[Create company contact](https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2625-6319&node-type=canvas&m=dev)

#### Tasks

- [ ] Create contact type selection component
- [ ] company contact
- [ ] Create and implement the avatar upload component
- [ ] Create the form component
- [ ] Integrate document file upload component
