### ISSUE TITLE
Refactor contacts list screen

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#116]
### Refactor contacts list screen

We've gotten a new design for the contacts list screen. In this page, the user will be able to see all their contacts and search for a specific contact, as well as to access the screen where they can create a new one.

There are two variations for this screen: one for when the user has contacts and another for when they don't have any contacts yet, the empty state. Those already exist in the project, so we must use the existing structure, but change the layout.

#### Files

[Overview.tsx](https://github.com/BitcreditProtocol/E-Bill-frontend/blob/main/src/pages/contacts/Overview.tsx)

#### Design references

https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2818-20916&node-type=frame&m=dev

#### Tasks

- [ ] Refactor the empty state layout
- [ ] Refactor the contacts list components
- [ ] Add the search input
- [ ] Add the button to trigger the new contact creation flow
- [ ] alphabetical sorting
- [ ] mockups
