### ISSUE TITLE
Select contact screen

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#117]
### Select contact screen

In many parts of the app, we need to select a contact to perform some action. This screen will be used to select a contact from the list of previously created contacts.

The screen must display the complete contact's information, a button to switch to the edit contact screen, and a button to confirm the contact selection.

#### Design references

https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2818-21044&node-type=frame&m=dev

#### Tasks

- [ ] Create the information visualization component
- [ ] Add the edit contact button
- [ ] Add the confirm contact selection button

#### Resources

We might want to implement this by using a Portal and/or a context:

https://react.dev/reference/react-dom/createPortal
