### ISSUE TITLE
View contact screen

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#118]
### View contact screen

The view contact screen allows an user to visualize the information related to one of their contacts. It also allows the user to trigger the edit contact screen.

The view must also have a button that allows the user to delete the contact. This button must trigger a drawer component, that asks the user to either confirm or cancel the deletion process.

#### Design references

[View contact](https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2818-21084&node-type=frame&m=dev)

[Delete contact](https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2853-7935&node-type=frame&m=dev)

#### Tasks

- [ ] Create the information visualization component
- [ ] Add the edit contact button
- [ ] Add the delete contact button
- [ ] Implement the delete contact drawer
- [ ] file preview
- [ ] mockups

#### Resources

We might want to use the existing Drawer component provided by shadcn, and update the styles to match our design system: https://ui.shadcn.com/docs/components/drawer
